### ISSUE TITLE
Download images from server

### ISSUE THREAD

**Issue by d3v1anX** [KevinTrevor/task_wget_novicom#1]
Hey Kevin, thank you for adding me on this repository. 

Could you get the images as well please? 

Thank you very much :)

![CleanShot 2023-08-31 at 07 20 41@2x](https://github.com/KevinTrevor/task_wget_novicom/assets/21339066/6816bc07-f96f-4cbe-b5d2-2c99b721e9e4)
![CleanShot 2023-08-31 at 07 20 31@2x](https://github.com/KevinTrevor/task_wget_novicom/assets/21339066/6ff61950-2e0e-40e5-8856-5f9461509a12)

**Comment by KevinTrevor** [comment]
Good evening, Mr. Patrick. I have been able to change all the images from URL to local files. I look forward to your response and possible corrections.
