### ISSUE TITLE
Not all Resources deleted (or local)

### ISSUE THREAD

**Issue by d3v1anX** [KevinTrevor/task_wget_novicom#2]
Hey Kevin, 

thanks for optimizing - unfortunately there are some urls, which are only called from the live environment, not from local. 
Could you check these please?

Thank you very much!

![CleanShot 2023-09-01 at 11 24 07](https://github.com/KevinTrevor/task_wget_novicom/assets/21339066/b33733f5-4008-44d9-afc6-ecc948ff3ac5)

**Comment by KevinTrevor** [comment]
Ok, these are the fonts of the page. I'll download them and make them local!
